#!/usr/bin/env bash
#
# create-branch - Create branch, pushes to remote
#
# $ git create-branch new-branch
# $ git create-branch new-branch old-branch
# $ git create-branch new-branch old-branch origin
#


case $# in
  1)
    BRANCH=$1
    START=HEAD
    REMOTE=origin
    ;;
  2)
    BRANCH=$1
    START=$2
    REMOTE=origin
    ;;
  3)
    BRANCH=$1
    START=$2
    REMOTE=$3
    ;;
  *)
    echo "usage: git create-branch <branch name> [<starting point>] [<remote]>"
    exit 99
    ;;
esac



git push $REMOTE $START:refs/heads/$BRANCH
git fetch $REMOTE
git checkout --track -b $BRANCH $REMOTE/$BRANCH
exit $?
