#!/usr/bin/env bash
#
# since - List commits since a given time
#
# $ git since
# $ git since "5 hours ago"
#

: ${SINCE:='last week'}

if [ $? -gt 0 ]; then
  SINCE=$1
fi

echo "==== Commits Since ${SINCE} ===="
git log --pretty='%an - %s' --after="${SINCE}"
