#!/usr/bin/env bash
#
# file-version - Show a file based on a commit/branch/ref
#
# $ git file-version 1234567 CHANGELOG.md
# $ git file-version trunk CHANGELOG.md
#

case $# in
  1)
    git show HEAD~1:$1
    ;;
  2)
    git show $1:$2
    ;;
  *)
    echo "usage: git file-version [<ref>] <file-path>"
    exit 1
    ;;
esac

