#!/usr/bin/env bash
#
# graph - Show graph of commits
#
# $ git graph
# $ git graph --all
# $ git graph origin/trunk
#

git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)' $@
