#!/usr/bin/env bash

if [[ "$@" == *"--help"* ]]; then
  echo "usage: git delete-remote [<remote>] <branch>"
  exit 0
fi

case $# in
  1)
    git push origin --delete $1
    exit $?
    ;;
  2)
    git push $1 --delete $2
    exit $?
    ;;
  *)
    echo "usage: git delete-remote [<remote>] <branch>"
    exit 1
    ;;
esac

